name: Multi-Arch Docker Build

inputs:
  cache:
    required: false
    default: 'false'
  context:
    required: true
  token:
    required: true
  username:
    required: true

runs:
  using: composite
  steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
      with:
        platforms: amd64,arm64

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2

    - name: Available Platforms
      shell: bash
      run: echo ${{ steps.buildx.outputs.platforms }}

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ inputs.username }}
        password: ${{ inputs.token }}
    
    - name: Build and Push w/ Cache
      if: inputs.cache == 'true'
      uses: docker/build-push-action@v3
      with:
        context: ${{ inputs.context }}
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ${{ inputs.username }}/${{ inputs.context }}:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Build and Push w/o Cache
      if: inputs.cache != 'true'
      uses: docker/build-push-action@v3
      with:
        context: ${{ inputs.context }}
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ${{ inputs.username }}/${{ inputs.context }}:latest
