name: dnsmasq

on:
  pull_request:
    types: [ opened, synchronize ]
    paths:
    - '.github/actions/docker-build/**'
    - '.github/workflows/dnsmasq.yml'
    - 'dnsmasq/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Build & Push Docker Image
      uses: ./.github/actions/docker-build
      with:
        context: dnsmasq
        tags: ${{ github.repository_owner }}/dnsmasq:latest
        token: ${{ secrets.DOCKERHUB_TOKEN }}
        username: ${{ secrets.DOCKERHUB_USERNAME }}
