name: img2pdf

on:
  push:
    branches: [ master ]
    paths:
    - '.github/actions/docker-build/**'
    - '.github/workflows/img2pdf.yml'
    - 'img2pdf/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Build & Push Docker Image
      uses: ./.github/actions/docker-build
      with:
        context: img2pdf
        tags: ${{ github.repository_owner }}/img2pdf:latest
        token: ${{ secrets.DOCKERHUB_TOKEN }}
        username: ${{ secrets.DOCKERHUB_USERNAME }}
