name: Docker symfony-php CI

on:
  schedule:
    - cron: '15 7 * * 1/14'
  workflow_dispatch:

jobs:
  php:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    # - name: Run Snyk to check Docker image for vulnerabilities
    #   uses: snyk/actions/docker@master
    #   continue-on-error: true
    #   env:
    #     SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
    #   with:
    #     image: rolandrajko/symfony-php
    #     args: --file=php/Dockerfile
    # - name: Upload result to GitHub Code Scanning
    #   uses: github/codeql-action/upload-sarif@v1
    #   with:
    #     sarif_file: snyk.sarif
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: ./php
        push: true
        tags: rolandrajko/symfony-php
