name: Docker symfony-php CI

on:
  schedule:
    - cron: '15 7 * * 1/14'
  workflow_dispatch:

jobs:
  php:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
      with:
        platforms: amd64,arm64

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2

    - name: Available Platforms
      run: echo ${{ steps.buildx.outputs.platforms }}

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build & Push Docker image
      run: |
        docker buildx build \
          --tag rolandrajko/symfony-php:latest \
          --platform=linux/amd64,linux/arm64 \
          --push .
      working-directory: symfony-php
